import { User1, User2, User3 } from "@Assets/index";

export const chatDataDummy = [
    {
        id: 15,
        type: "INDIVIDUAL",
        status: "ACTIVE",
        creatorId: 35,
        lastEventId: 111,
        createdAt: "2024-05-21T09:53:58.394Z",
        updatedAt: "2024-05-21T09:54:02.522Z",
        deletedAt: null,
        creator: {
            id: 35,
            email: "aun@gmail.com",
            firstName: "aun",
            lastName: "muhammad",
            displayName: "aun muhammad",
            type: "USER",
            status: "ACTIVE",
            gatewayAccountId: null,
            gatewayAccountStatus: "INACTIVE",
            gatewayCustomerId: null,
            termAndCondition: true,
            isOnline: true,
            createdAt: "2024-05-21T09:53:19.120Z",
            updatedAt: "2024-05-21T09:53:20.093Z",
            deletedAt: null,
            userDetail: {
                id: 31,
                userId: 35,
                state: null,
                country: "Pakistan",
                city: "karachi",
                description: null,
                dob: null,
                phone: "+11232132323",
                countryCode: "us",
                zipCode: null,
                profilePictureId: null,
                documentId: null,
                createdAt: "2024-05-21T09:53:19.145Z",
                updatedAt: "2024-05-21T09:53:19.145Z",
                deletedAt: null,
                profilePicture: null
            }
        },
        participants: [
            {
                id: 30,
                chatId: 15,
                userId: 30,
                lastReadEventId: null,
                lastDeliveredEventId: null,
                userType: "HOST",
                createdAt: "2024-05-21T09:53:58.411Z",
                updatedAt: "2024-05-21T09:53:58.411Z",
                deletedAt: null,
                user: {
                    id: 30,
                    email: "muhammad.raafay@koderlabs.com",
                    firstName: "Muhammad",
                    lastName: "Raafay",
                    displayName: "Muhammad Raafay",
                    type: "USER",
                    status: "ACTIVE",
                    gatewayAccountId: "acct_1OrLixQn2SkYAqpr",
                    gatewayAccountStatus: "ACTIVE",
                    gatewayCustomerId: null,
                    termAndCondition: true,
                    isOnline: false,
                    createdAt: "2024-03-05T14:25:52.303Z",
                    updatedAt: "2024-03-08T16:02:53.521Z",
                    deletedAt: null,
                    userDetail: {
                        id: 26,
                        userId: 30,
                        state: null,
                        country: "United States",
                        city: "New York",
                        description: "Hello world",
                        dob: "2006-03-03T00:00:00.000Z",
                        phone: "+12222222222",
                        countryCode: "us",
                        zipCode: null,
                        profilePictureId: 100,
                        documentId: 101,
                        createdAt: "2024-03-05T14:25:52.322Z",
                        updatedAt: "2024-03-06T13:44:39.192Z",
                        deletedAt: null,
                        profilePicture: {
                            id: 100,
                            name: "alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            extension: "jpg",
                            type: "IMAGE",
                            access: "PUBLIC",
                            size: 583.69140625,
                            location: "https://ionpropertiesstaging.s3.us-west-2.amazonaws.com/",
                            path: "media/IMAGE/2024/3/5/360__89e5fe7c-2d80-422d-b380-d046acb8db7f__alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            thumbPath:
                                "media/IMAGE/2024/3/5/360__89e5fe7c-2d80-422d-b380-d046acb8db7f__alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            status: "READY",
                            meta: null,
                            userId: null,
                            createdAt: "2024-03-05T14:25:45.363Z",
                            updatedAt: "2024-03-05T14:25:49.953Z",
                            deletedAt: null
                        }
                    }
                }
            }
        ],
        lastEvent: {
            id: 111,
            type: "USER_EVENT",
            chatId: 15,
            senderId: 35,
            content: "hello",
            isRead: false,
            createdAt: "2024-05-21T14:55:28+05:00",
            updatedAt: "2024-05-21T09:54:02.522Z",
            deletedAt: null,
            sender: {
                id: 35,
                email: "aun@gmail.com",
                firstName: "aun",
                lastName: "muhammad",
                displayName: "aun muhammad",
                type: "USER",
                status: "ACTIVE",
                gatewayAccountId: null,
                gatewayAccountStatus: "INACTIVE",
                gatewayCustomerId: null,
                termAndCondition: true,
                isOnline: true,
                createdAt: "2024-05-21T09:53:19.120Z",
                updatedAt: "2024-05-21T09:53:20.093Z",
                deletedAt: null,
                userDetail: {
                    id: 31,
                    userId: 35,
                    state: null,
                    country: "Pakistan",
                    city: "karachi",
                    description: null,
                    dob: null,
                    phone: "+11232132323",
                    countryCode: "us",
                    zipCode: null,
                    profilePictureId: null,
                    documentId: null,
                    createdAt: "2024-05-21T09:53:19.145Z",
                    updatedAt: "2024-05-21T09:53:19.145Z",
                    deletedAt: null,
                    profilePicture: null
                }
            },
            attachments: []
        },
        sentByUser: true,
        receiverUser: {
            id: 30,
            email: "muhammad.raafay@koderlabs.com",
            firstName: "Muhammad",
            lastName: "Raafay",
            displayName: "Muhammad Raafay",
            type: "USER",
            status: "ACTIVE",
            gatewayAccountId: "acct_1OrLixQn2SkYAqpr",
            gatewayAccountStatus: "ACTIVE",
            gatewayCustomerId: null,
            termAndCondition: true,
            isOnline: true,
            createdAt: "2024-03-05T14:25:52.303Z",
            updatedAt: "2024-03-08T16:02:53.521Z",
            deletedAt: null,
            userDetail: {
                id: 26,
                userId: 30,
                state: null,
                country: "United States",
                city: "New York",
                description: "Hello world",
                dob: "2006-03-03T00:00:00.000Z",
                phone: "+12222222222",
                countryCode: "us",
                zipCode: null,
                profilePictureId: 100,
                documentId: 101,
                createdAt: "2024-03-05T14:25:52.322Z",
                updatedAt: "2024-03-06T13:44:39.192Z",
                deletedAt: null,
                profilePicture: User1
            }
        }
    },
    {
        id: 17,
        type: "INDIVIDUAL",
        status: "ACTIVE",
        creatorId: 35,
        lastEventId: 111,
        createdAt: "2024-05-21T09:53:58.394Z",
        updatedAt: "2024-05-21T09:54:02.522Z",
        deletedAt: null,
        creator: {
            id: 35,
            email: "aun@gmail.com",
            firstName: "aun",
            lastName: "muhammad",
            displayName: "aun muhammad",
            type: "USER",
            status: "ACTIVE",
            gatewayAccountId: null,
            gatewayAccountStatus: "INACTIVE",
            gatewayCustomerId: null,
            termAndCondition: true,
            isOnline: true,
            createdAt: "2024-05-21T09:53:19.120Z",
            updatedAt: "2024-05-21T09:53:20.093Z",
            deletedAt: null,
            userDetail: {
                id: 31,
                userId: 35,
                state: null,
                country: "Pakistan",
                city: "karachi",
                description: null,
                dob: null,
                phone: "+11232132323",
                countryCode: "us",
                zipCode: null,
                profilePictureId: null,
                documentId: null,
                createdAt: "2024-05-21T09:53:19.145Z",
                updatedAt: "2024-05-21T09:53:19.145Z",
                deletedAt: null,
                profilePicture: null
            }
        },
        participants: [
            {
                id: 30,
                chatId: 15,
                userId: 30,
                lastReadEventId: null,
                lastDeliveredEventId: null,
                userType: "HOST",
                createdAt: "2024-05-21T09:53:58.411Z",
                updatedAt: "2024-05-21T09:53:58.411Z",
                deletedAt: null,
                user: {
                    id: 30,
                    email: "muhammad.raafay@koderlabs.com",
                    firstName: "Muhammad",
                    lastName: "Raafay",
                    displayName: "Stephen Yustino",
                    type: "USER",
                    status: "ACTIVE",
                    gatewayAccountId: "acct_1OrLixQn2SkYAqpr",
                    gatewayAccountStatus: "ACTIVE",
                    gatewayCustomerId: null,
                    termAndCondition: true,
                    isOnline: true,
                    createdAt: "2024-03-05T14:25:52.303Z",
                    updatedAt: "2024-03-08T16:02:53.521Z",
                    deletedAt: null,
                    userDetail: {
                        id: 26,
                        userId: 30,
                        state: null,
                        country: "United States",
                        city: "New York",
                        description: "Hello world",
                        dob: "2006-03-03T00:00:00.000Z",
                        phone: "+12222222222",
                        countryCode: "us",
                        zipCode: null,
                        profilePictureId: 100,
                        documentId: 101,
                        createdAt: "2024-03-05T14:25:52.322Z",
                        updatedAt: "2024-03-06T13:44:39.192Z",
                        deletedAt: null,
                        profilePicture: {
                            id: 100,
                            name: "alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            extension: "jpg",
                            type: "IMAGE",
                            access: "PUBLIC",
                            size: 583.69140625,
                            location: "https://ionpropertiesstaging.s3.us-west-2.amazonaws.com/",
                            path: "media/IMAGE/2024/3/5/360__89e5fe7c-2d80-422d-b380-d046acb8db7f__alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            thumbPath:
                                "media/IMAGE/2024/3/5/360__89e5fe7c-2d80-422d-b380-d046acb8db7f__alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            status: "READY",
                            meta: null,
                            userId: null,
                            createdAt: "2024-03-05T14:25:45.363Z",
                            updatedAt: "2024-03-05T14:25:49.953Z",
                            deletedAt: null
                        }
                    }
                }
            }
        ],
        lastEvent: {
            id: 111,
            type: "USER_EVENT",
            chatId: 15,
            senderId: 35,
            content: "hello",
            isRead: true,
            createdAt: "2024-05-21T14:55:28+05:00",
            updatedAt: "2024-05-21T09:54:02.522Z",
            deletedAt: null,
            sender: {
                id: 35,
                email: "aun@gmail.com",
                firstName: "aun",
                lastName: "muhammad",
                displayName: "aun muhammad",
                type: "USER",
                status: "ACTIVE",
                gatewayAccountId: null,
                gatewayAccountStatus: "INACTIVE",
                gatewayCustomerId: null,
                termAndCondition: true,
                isOnline: true,
                createdAt: "2024-05-21T09:53:19.120Z",
                updatedAt: "2024-05-21T09:53:20.093Z",
                deletedAt: null,
                userDetail: {
                    id: 31,
                    userId: 35,
                    state: null,
                    country: "Pakistan",
                    city: "karachi",
                    description: null,
                    dob: null,
                    phone: "+11232132323",
                    countryCode: "us",
                    zipCode: null,
                    profilePictureId: null,
                    documentId: null,
                    createdAt: "2024-05-21T09:53:19.145Z",
                    updatedAt: "2024-05-21T09:53:19.145Z",
                    deletedAt: null,
                    profilePicture: null
                }
            },
            attachments: []
        },
        sentByUser: true,
        receiverUser: {
            id: 30,
            email: "muhammad.raafay@koderlabs.com",
            firstName: "Muhammad",
            lastName: "Raafay",
            displayName: "Stephen Yustino",
            type: "USER",
            status: "ACTIVE",
            gatewayAccountId: "acct_1OrLixQn2SkYAqpr",
            gatewayAccountStatus: "ACTIVE",
            gatewayCustomerId: null,
            termAndCondition: true,
            isOnline: false,
            createdAt: "2024-03-05T14:25:52.303Z",
            updatedAt: "2024-03-08T16:02:53.521Z",
            deletedAt: null,
            userDetail: {
                id: 26,
                userId: 30,
                state: null,
                country: "United States",
                city: "New York",
                description: "Hello world",
                dob: "2006-03-03T00:00:00.000Z",
                phone: "+12222222222",
                countryCode: "us",
                zipCode: null,
                profilePictureId: 100,
                documentId: 101,
                createdAt: "2024-03-05T14:25:52.322Z",
                updatedAt: "2024-03-06T13:44:39.192Z",
                deletedAt: null,
                profilePicture: User2
            }
        }
    },
    {
        id: 16,
        type: "INDIVIDUAL",
        status: "ACTIVE",
        creatorId: 35,
        lastEventId: 111,
        createdAt: "2024-05-21T09:53:58.394Z",
        updatedAt: "2024-05-21T09:54:02.522Z",
        deletedAt: null,
        creator: {
            id: 35,
            email: "aun@gmail.com",
            firstName: "aun",
            lastName: "muhammad",
            displayName: "aun muhammad",
            type: "USER",
            status: "ACTIVE",
            gatewayAccountId: null,
            gatewayAccountStatus: "INACTIVE",
            gatewayCustomerId: null,
            termAndCondition: true,
            isOnline: true,
            createdAt: "2024-05-21T09:53:19.120Z",
            updatedAt: "2024-05-21T09:53:20.093Z",
            deletedAt: null,
            userDetail: {
                id: 31,
                userId: 35,
                state: null,
                country: "Pakistan",
                city: "karachi",
                description: null,
                dob: null,
                phone: "+11232132323",
                countryCode: "us",
                zipCode: null,
                profilePictureId: null,
                documentId: null,
                createdAt: "2024-05-21T09:53:19.145Z",
                updatedAt: "2024-05-21T09:53:19.145Z",
                deletedAt: null,
                profilePicture: null
            }
        },
        participants: [
            {
                id: 30,
                chatId: 15,
                userId: 30,
                lastReadEventId: null,
                lastDeliveredEventId: null,
                userType: "HOST",
                createdAt: "2024-05-21T09:53:58.411Z",
                updatedAt: "2024-05-21T09:53:58.411Z",
                deletedAt: null,
                user: {
                    id: 30,
                    email: "muhammad.raafay@koderlabs.com",
                    firstName: "Muhammad",
                    lastName: "Raafay",
                    displayName: "Stephen Yustino",
                    type: "USER",
                    status: "ACTIVE",
                    gatewayAccountId: "acct_1OrLixQn2SkYAqpr",
                    gatewayAccountStatus: "ACTIVE",
                    gatewayCustomerId: null,
                    termAndCondition: true,
                    isOnline: false,
                    createdAt: "2024-03-05T14:25:52.303Z",
                    updatedAt: "2024-03-08T16:02:53.521Z",
                    deletedAt: null,
                    userDetail: {
                        id: 26,
                        userId: 30,
                        state: null,
                        country: "United States",
                        city: "New York",
                        description: "Hello world",
                        dob: "2006-03-03T00:00:00.000Z",
                        phone: "+12222222222",
                        countryCode: "us",
                        zipCode: null,
                        profilePictureId: 100,
                        documentId: 101,
                        createdAt: "2024-03-05T14:25:52.322Z",
                        updatedAt: "2024-03-06T13:44:39.192Z",
                        deletedAt: null,
                        profilePicture: {
                            id: 100,
                            name: "alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            extension: "jpg",
                            type: "IMAGE",
                            access: "PUBLIC",
                            size: 583.69140625,
                            location: "https://ionpropertiesstaging.s3.us-west-2.amazonaws.com/",
                            path: "media/IMAGE/2024/3/5/360__89e5fe7c-2d80-422d-b380-d046acb8db7f__alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            thumbPath:
                                "media/IMAGE/2024/3/5/360__89e5fe7c-2d80-422d-b380-d046acb8db7f__alexsuprunZHvM3XIOHoEunsplash(1).jpg",
                            status: "READY",
                            meta: null,
                            userId: null,
                            createdAt: "2024-03-05T14:25:45.363Z",
                            updatedAt: "2024-03-05T14:25:49.953Z",
                            deletedAt: null
                        }
                    }
                }
            }
        ],
        lastEvent: {
            id: 111,
            type: "USER_EVENT",
            chatId: 15,
            senderId: 35,
            content: "hello",
            isRead: false,
            createdAt: "2024-05-21T14:55:28+05:00",
            updatedAt: "2024-05-21T09:54:02.522Z",
            deletedAt: null,
            sender: {
                id: 35,
                email: "aun@gmail.com",
                firstName: "aun",
                lastName: "muhammad",
                displayName: "aun muhammad",
                type: "USER",
                status: "ACTIVE",
                gatewayAccountId: null,
                gatewayAccountStatus: "INACTIVE",
                gatewayCustomerId: null,
                termAndCondition: true,
                isOnline: true,
                createdAt: "2024-05-21T09:53:19.120Z",
                updatedAt: "2024-05-21T09:53:20.093Z",
                deletedAt: null,
                userDetail: {
                    id: 31,
                    userId: 35,
                    state: null,
                    country: "Pakistan",
                    city: "karachi",
                    description: null,
                    dob: null,
                    phone: "+11232132323",
                    countryCode: "us",
                    zipCode: null,
                    profilePictureId: null,
                    documentId: null,
                    createdAt: "2024-05-21T09:53:19.145Z",
                    updatedAt: "2024-05-21T09:53:19.145Z",
                    deletedAt: null,
                    profilePicture: null
                }
            },
            attachments: []
        },
        sentByUser: true,
        receiverUser: {
            id: 30,
            email: "muhammad.raafay@koderlabs.com",
            firstName: "Muhammad",
            lastName: "Raafay",
            displayName: "Stephen Yustino",
            type: "USER",
            status: "ACTIVE",
            gatewayAccountId: "acct_1OrLixQn2SkYAqpr",
            gatewayAccountStatus: "ACTIVE",
            gatewayCustomerId: null,
            termAndCondition: true,
            isOnline: false,
            createdAt: "2024-03-05T14:25:52.303Z",
            updatedAt: "2024-03-08T16:02:53.521Z",
            deletedAt: null,
            userDetail: {
                id: 26,
                userId: 30,
                state: null,
                country: "United States",
                city: "New York",
                description: "Hello world",
                dob: "2006-03-03T00:00:00.000Z",
                phone: "+12222222222",
                countryCode: "us",
                zipCode: null,
                profilePictureId: 100,
                documentId: 101,
                createdAt: "2024-03-05T14:25:52.322Z",
                updatedAt: "2024-03-06T13:44:39.192Z",
                deletedAt: null,
                profilePicture: User3
            }
        }
    }
];
