import PromptChat from "@Pages/AppScreens/PromptChat";

export const NavigationRoutes = {
  AUTH_ROUTES: {
    INDEX:'/',
    LOGIN: "/login",
    VERIFY_EMAIL: "/otp",
    REGISTER: "/register",
    RESET_PASSWORD: "/reset-password",
    FORGOT_PASSWORD: "/forgot-password",
    VALIDATE_DATABASE: "/validate-database",
    LANDING_PAGE: "/home",
    CONTACT_US : "/contact-us",
    PRIVACY_POLICY : "/privacy-policy",
    PRICING : "/pricing",
    ABOUT_US: "/about-us",
    FAQ: "/faq",
  },
  DASHBOARD_ROUTES: {
    DASHBOARD: "/dashboard",
    CHAT: "/chat",
    CHAT_DETAILS: "/chat/:id",
    MY_EARNINGGS:"/my-earnings",
    ORDER_MANAGEMENT:"/order-management",
    ORDER_DETAILS:"/order-management/:id",
    GENERATE_LABELS_MAIN: "/order-management/generate-labels",
    GENERATE_LABELS: "/order-management/generate-labels/:id",
    PAYMENT_DETAILS:"/payment-details",
    PRODUCT_MANAGEMENT:"/product-management",
    PRODUCT_DETAILS: "/product-management/product-details",
    ADD_PRODUCT: "/product-management/add-product",
    PRODUCT_EDIT: "/product-management/product-edit",
    BANNER_MANAGEMENT:"/banner-ad-management",
    BANNER_MANAGEMENT_DETAILS:"/banner-ad-management/banner-details",
    REQUEST_BANNER:"/banner-ad-management/request-banner",
    CHANGE_PASSWORD:"change-password",
    EDIT_PROFILE:"edit-profile",
    USER_MANAGEMENT:"/user-management",
    REQUEST_MANAGEMENT:"/request-management",
    PROMPT_CHAT:"/prompt-chat",
    EMPLOYEE_PROMPT_CHAT:"employee-prompt-chat",
    ADD_NEW_GRAPH:"/add-new-graph",
    ADD_NEW_EMPLOYEE:"/add-new-employee",
    EMPLOYEE_LISTING:"/employee-listing",
    EMPLOYEE_DETAIL:"/employee-detail",
    UPDATE_EMPLOYEE:"/employee",
    EMPLOYEE: "/employee",
    ROLE_MANAGEMENT:"/role-management",
  },
};
